# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\myProj\test\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1161, 736)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setWindowFilePath("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.create_file_btn = QtWidgets.QPushButton(self.centralwidget)
        self.create_file_btn.setGeometry(QtCore.QRect(250, 0, 901, 41))
        self.create_file_btn.setObjectName("create_file_btn")
        self.create_file_btn_gr = QtWidgets.QPushButton(self.centralwidget)
        self.create_file_btn_gr.setGeometry(QtCore.QRect(250, 60, 901, 41))
        self.create_file_btn_gr.setAutoDefault(True)
        self.create_file_btn_gr.setObjectName("create_file_btn_gr")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(454, 190, 251, 171))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionXML_type = QtWidgets.QAction(MainWindow)
        self.actionXML_type.setObjectName("actionXML_type")
        self.actionJSON_type = QtWidgets.QAction(MainWindow)
        self.actionJSON_type.setObjectName("actionJSON_type")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.create_file_btn.setText(_translate("MainWindow", "Create PickList"))
        self.create_file_btn_gr.setText(_translate("MainWindow", "Create Good Receival"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.actionXML_type.setText(_translate("MainWindow", "XML type"))
        self.actionJSON_type.setText(_translate("MainWindow", "JSON type"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
